server:
    port: 5100
    error:
        include-stacktrace: never

spring:
    application:
      name: card-api
    profiles:
      active: ${PROFILES_ACTIVE:dev}

security:
    oauth2:
        resource:
            user-info-uri: http://200.171.251.125:25565/me
        client:
            access-token-uri: http://localhost:25565/oauth/token
            client-id: api
            client-secret: api123
            grant-type: client_credentials
