server:
    port: 5100
    error:
        include-stacktrace: never

spring:
    application:
      name: card-api
    profiles:
      active: ${PROFILES_ACTIVE:dev}
    cloud:
        consul:
        host: localhost
        port: 8500
        failFast: false