server:
    port: ${PORT:9080}

spring:
    application:
        name: gateway-service
    cloud:
        consul:
            host: ${SERVICE_DISCOVERY_SERVER_ADDRESS}
            port: ${SERVICE_DISCOVERY_SERVER_PORT}
        gateway:
            discovery:
                locator:
                    enabled: true
                routes:
                    - id: localhost-docker
                      uri: ${LOCAL_ADDRESS}:${PORT:9080}

logging.level.com.netflix: DEBUG

management:
    security:
        enabled: false